// ============================================================
// KEMO MARKET — Données Produits (Simulées)
// Marketplace Afro-Luxe — Lomé, Togo
// ============================================================

const KEMO_PRODUCTS = [
  { id: 1, name: "Ensemble Kente Prestige Homme", category: "mode", price: 45000, originalPrice: 62000, discount: 27, rating: 4.8, reviews: 134, sold: 342, stock: 15, emoji: "\ud83d\udc54", badge: "BEST SELLER", badgeColor: "gold", description: "Ensemble deux pi\u00e8ces en tissu kente authentique du Ghana.", tags: ["kente", "africain", "homme", "c\u00e9r\u00e9monie"], seller: { name: "Adjo Cr\u00e9ations", rating: 4.9, sales: 1240, verified: true, city: "Lom\u00e9" }, featured: true, flash: false, new: false },
  { id: 2, name: "Robe Wax Femme Lumi\u00e8re d'Afrique", category: "mode", price: 28500, originalPrice: 35000, discount: 19, rating: 4.9, reviews: 287, sold: 891, stock: 8, emoji: "\ud83d\udc57", badge: "COUP DE C\u0152UR", badgeColor: "rose", description: "Robe longue en wax hollandais authentique.", tags: ["wax", "robe", "femme"], seller: { name: "Maison Akua", rating: 4.8, sales: 3200, verified: true, city: "Lom\u00e9" }, featured: true, flash: true, new: false },
  { id: 3, name: "Sneakers Cuir Artisanal Urban K\u00e9ra", category: "mode", price: 32000, originalPrice: 32000, discount: 0, rating: 4.6, reviews: 56, sold: 124, stock: 22, emoji: "\ud83d\udc5f", badge: "NOUVEAU", badgeColor: "green", description: "Sneakers en cuir v\u00e9ritable artisanales togo.", tags: ["chaussures", "cuir", "artisanal"], seller: { name: "K\u00e9ra Shoes", rating: 4.7, sales: 450, verified: true, city: "Lom\u00e9" }, featured: false, flash: false, new: true },
  { id: 4, name: "Smartphone Tecno Camon 30 Pro", category: "electronique", price: 185000, originalPrice: 215000, discount: 14, rating: 4.7, reviews: 412, sold: 1820, stock: 30, emoji: "\ud83d\udcf1", badge: "FLASH -14%", badgeColor: "red", description: "6.8\" AMOLED 120Hz, 50MP cam\u00e9ra IA, 5000mAh.", tags: ["smartphone", "tecno", "4G"], seller: { name: "TechLom\u00e9 Store", rating: 4.9, sales: 5600, verified: true, city: "Lom\u00e9" }, featured: true, flash: true, new: false },
  { id: 5, name: "\u00c9couteurs Sans-Fil Bluetooth Pro", category: "electronique", price: 18500, originalPrice: 25000, discount: 26, rating: 4.5, reviews: 198, sold: 567, stock: 45, emoji: "\ud83c\udfa7", badge: "PROMO", badgeColor: "gold", description: "True Wireless, r\u00e9duction de bruit active, 30h.", tags: ["\u00e9couteurs", "bluetooth"], seller: { name: "TechLom\u00e9 Store", rating: 4.9, sales: 5600, verified: true, city: "Lom\u00e9" }, featured: false, flash: true, new: false },
  { id: 6, name: "Panneau Solaire 200W + Batterie", category: "electronique", price: 145000, originalPrice: 170000, discount: 15, rating: 4.8, reviews: 89, sold: 203, stock: 12, emoji: "\u2600\ufe0f", badge: "POPULAIRE", badgeColor: "gold", description: "Kit complet \u00e9nergie solaire 200W + batterie 100Ah.", tags: ["solaire", "\u00e9nergie"], seller: { name: "SolaireTogo", rating: 4.8, sales: 890, verified: true, city: "Lom\u00e9" }, featured: true, flash: false, new: false },
  { id: 7, name: "Huile de Karit\u00e9 Pure Bio Nourissa", category: "beaute", price: 8500, originalPrice: 12000, discount: 29, rating: 4.9, reviews: 634, sold: 4210, stock: 200, emoji: "\ud83e\udeb4", badge: "N\u00b01 VENTES", badgeColor: "gold", description: "Karit\u00e9 pur non raffin\u00e9 du Burkina Faso. 100% naturel.", tags: ["karit\u00e9", "naturel", "bio"], seller: { name: "Nourissa Naturals", rating: 5.0, sales: 8900, verified: true, city: "Lom\u00e9" }, featured: true, flash: false, new: false },
  { id: 8, name: "Kit Maquillage Teintes Africaines", category: "beaute", price: 25000, originalPrice: 32000, discount: 22, rating: 4.7, reviews: 178, sold: 892, stock: 35, emoji: "\ud83d\udc84", badge: "FLASH", badgeColor: "red", description: "Kit professionnel 20 pi\u00e8ces pour peaux noires.", tags: ["maquillage", "kit", "professionnel"], seller: { name: "Glam Africa", rating: 4.8, sales: 2100, verified: true, city: "Lom\u00e9" }, featured: false, flash: true, new: false },
  { id: 9, name: "Tableau Afro-Art Reine de Saba", category: "maison", price: 35000, originalPrice: 35000, discount: 0, rating: 4.9, reviews: 43, sold: 67, stock: 5, emoji: "\ud83d\uddbc\ufe0f", badge: "ARTISANAT", badgeColor: "gold", description: "Oeuvre originale peinte \u00e0 la main par artiste togolais.", tags: ["art", "tableau", "africain"], seller: { name: "Atelier Koffi", rating: 4.9, sales: 340, verified: true, city: "Lom\u00e9" }, featured: true, flash: false, new: false },
  { id: 10, name: "Climatiseur Inverter 1.5CV", category: "maison", price: 245000, originalPrice: 290000, discount: 16, rating: 4.6, reviews: 156, sold: 312, stock: 18, emoji: "\u2744\ufe0f", badge: "FLASH -16%", badgeColor: "red", description: "Climatiseur Inverter A++ 1.5CV. Installation incluse.", tags: ["climatiseur", "inverter"], seller: { name: "\u00c9lectro Plus", rating: 4.7, sales: 1800, verified: true, city: "Lom\u00e9" }, featured: true, flash: true, new: false },
  { id: 11, name: "Caf\u00e9 Robusta Togo Premium 500g", category: "alimentation", price: 6500, originalPrice: 8000, discount: 19, rating: 4.8, reviews: 234, sold: 1560, stock: 150, emoji: "\u2615", badge: "LOCAL", badgeColor: "green", description: "Caf\u00e9 robusta des plateaux togolais, torr\u00e9faction artisanale.", tags: ["caf\u00e9", "togolais", "local"], seller: { name: "Caf\u00e9 des Plateaux", rating: 4.9, sales: 4200, verified: true, city: "Kpalim\u00e9" }, featured: false, flash: false, new: false },
  { id: 12, name: "Panier \u00c9picerie Fine Africaine", category: "alimentation", price: 42000, originalPrice: 55000, discount: 24, rating: 4.7, reviews: 87, sold: 234, stock: 25, emoji: "\ud83e\uddf4", badge: "CADEAU ID\u00c9AL", badgeColor: "gold", description: "Panier premium 12 produits s\u00e9lectionn\u00e9s.", tags: ["\u00e9picerie", "panier", "cadeau"], seller: { name: "Terroir Togo", rating: 4.8, sales: 780, verified: true, city: "Lom\u00e9" }, featured: true, flash: true, new: false }
];

const KEMO_CATEGORIES = [
  { id: "tous", label: "Tous les produits", icon: "\ud83c\udfaa", count: KEMO_PRODUCTS.length },
  { id: "mode", label: "Mode & Style", icon: "\ud83d\udc57", count: 3 },
  { id: "electronique", label: "High-Tech", icon: "\ud83d\udcf1", count: 3 },
  { id: "beaute", label: "Beaut\u00e9 & Soins", icon: "\ud83d\udc84", count: 2 },
  { id: "maison", label: "Maison & D\u00e9co", icon: "\ud83c\udfe0", count: 2 },
  { id: "alimentation", label: "Alimentation", icon: "\ud83e\udd57", count: 2 }
];

function getProductById(id) { return KEMO_PRODUCTS.find(p => p.id === parseInt(id)); }
function getProductsByCategory(cat) { if (cat === "tous") return KEMO_PRODUCTS; return KEMO_PRODUCTS.filter(p => p.category === cat); }
function getFeaturedProducts() { return KEMO_PRODUCTS.filter(p => p.featured); }
function getFlashProducts() { return KEMO_PRODUCTS.filter(p => p.flash); }
function formatPrice(price) { return new Intl.NumberFormat('fr-FR').format(price) + ' FCFA'; }
function searchProducts(query) { const q = query.toLowerCase(); return KEMO_PRODUCTS.filter(p => p.name.toLowerCase().includes(q) || p.description.toLowerCase().includes(q) || p.tags.some(t => t.includes(q))); }