[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "max-age=3600"